---
# tasks file for roles/crear_archivos
# ---
- name: Crear carpeta alumno
  file:
    path: /tmp/2do_parcial/alumno
    state: directory

- name: Crear carpeta equipo
  file:
    path: /tmp/2do_parcial/equipo
    state: directory

- name: Crear archivo datos_alumno.txt
  template:
    src: datos_alumno.j2
    dest: /tmp/2do_parcial/alumno/datos_alumno.txt

- name: Crear archivo datos_equipo.txt
  template:
    src: datos_equipo.j2
    dest: /tmp/2do_parcial/equipo/datos_equipo.txt

- name: Permitir sudo sin password a grupo 2PSupervisores
  copy:
    dest: /etc/sudoers.d/2psupervisores
    content: "%2PSupervisores ALL=(ALL) NOPASSWD: ALL\n"
    owner: root
    group: root
    mode: '0440'

